-- -------------------------------------------------------
-- Script de cr�ation des tables pour la BD du laboratoire
-- � ex�cuter dans Oracle SQL Developer
-- -------------------------------------------------------

-- 1) Suppression (utile pour r�-ex�cuter le script sans erreur)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PARTICIPER CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CONTRIBUER CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE FINANCE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PUBLICATION CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE LABORATOIRE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE EVENEMENT CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE PROJET CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE CHERCHEUR CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL; END;
/
-- Suppression des s�quences si elles existent
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CHERCHEUR'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PUBLICATION'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_PROJET'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_FINANCE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_LABORATOIRE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_EVENEMENT'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- 2) Table CHERCHEUR
CREATE TABLE CHERCHEUR (
  ID_CHERCHEUR    NUMBER        NOT NULL,
  NOM             VARCHAR2(100) NOT NULL,
  PRENOM          VARCHAR2(100),
  EMAIL           VARCHAR2(200),
  GRADE           VARCHAR2(50),
  CIN             VARCHAR2(30),
  PHOTO_PROFIL    VARCHAR2(200) DEFAULT ':/avatar.png',
  CONSTRAINT PK_CHERCHEUR PRIMARY KEY (ID_CHERCHEUR),
  CONSTRAINT UNQ_CHERCHEUR_EMAIL UNIQUE (EMAIL),
  CONSTRAINT UNQ_CHERCHEUR_CIN   UNIQUE (CIN)
);

CREATE SEQUENCE SEQ_CHERCHEUR START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
-- trigger pour remplir automatiquement ID_CHERCHEUR
CREATE OR REPLACE TRIGGER BI_CHERCHEUR
  BEFORE INSERT ON CHERCHEUR
  FOR EACH ROW
BEGIN
  IF :NEW.ID_CHERCHEUR IS NULL THEN
     SELECT SEQ_CHERCHEUR.NEXTVAL INTO :NEW.ID_CHERCHEUR FROM DUAL;
  END IF;
END;
/

-- 3) Table PUBLICATION
CREATE TABLE PUBLICATION (
  ID_PUBLICATION    NUMBER        NOT NULL,
  DOI               VARCHAR2(250) NOT NULL,
  TITRE             VARCHAR2(400) NOT NULL,
  AUTEUR            VARCHAR2(400),
  DATE_PUBLICATION  DATE,
  STATUT            VARCHAR2(30),
  REVUE             VARCHAR2(200),
  ID_CHERCHEUR      NUMBER,
  CONSTRAINT PK_PUBLICATION PRIMARY KEY (ID_PUBLICATION),
  CONSTRAINT UNQ_PUBLICATION_DOI UNIQUE (DOI),
  CONSTRAINT FK_PUBLICATION_CHERCHEUR FOREIGN KEY (ID_CHERCHEUR)
    REFERENCES CHERCHEUR (ID_CHERCHEUR) ON DELETE SET NULL,
  CONSTRAINT CK_PUBLICATION_STATUT CHECK (STATUT IN ('soumis','en_revision','accepte','publie','rejete'))
);

CREATE SEQUENCE SEQ_PUBLICATION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE OR REPLACE TRIGGER BI_PUBLICATION
  BEFORE INSERT ON PUBLICATION
  FOR EACH ROW
BEGIN
  IF :NEW.ID_PUBLICATION IS NULL THEN
     SELECT SEQ_PUBLICATION.NEXTVAL INTO :NEW.ID_PUBLICATION FROM DUAL;
  END IF;
END;
/

-- 4) Table PROJET (ID auto, CODE m�tier unique)
CREATE TABLE PROJET (
  ID_PROJET     NUMBER        NOT NULL,
  CODE          VARCHAR2(64)  NOT NULL,
  TITRE         VARCHAR2(400) NOT NULL,
  DATE_DEBUT    DATE,
  DATE_FIN      DATE,
  RESPONSABLE   NUMBER,
  ETAT          VARCHAR2(30),
  PROGRESSION   NUMBER(5,2),
  CONSTRAINT PK_PROJET PRIMARY KEY (ID_PROJET),
  CONSTRAINT UNQ_PROJET_CODE UNIQUE (CODE),
  CONSTRAINT FK_PROJET_RESPONSABLE FOREIGN KEY (RESPONSABLE)
    REFERENCES CHERCHEUR (ID_CHERCHEUR) ON DELETE SET NULL,
  CONSTRAINT CK_PROJET_ETAT CHECK (ETAT IN ('en_cours','termine','suspendu','annule')),
  CONSTRAINT CK_PROJET_PROGRESSION CHECK (PROGRESSION BETWEEN 0 AND 100)
);

CREATE SEQUENCE SEQ_PROJET START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE OR REPLACE TRIGGER BI_PROJET
  BEFORE INSERT ON PROJET
  FOR EACH ROW
BEGIN
  IF :NEW.ID_PROJET IS NULL THEN
     SELECT SEQ_PROJET.NEXTVAL INTO :NEW.ID_PROJET FROM DUAL;
  END IF;
END;
/

-- 5) Table FINANCE
CREATE TABLE FINANCE (
  ID_TRANSACTION  NUMBER        NOT NULL,
  MONTANT         NUMBER(12,2)  NOT NULL,
  TYPE_TRANS      VARCHAR2(50), -- type de transaction (ex: subvention, achat...)
  CATEGORIE       VARCHAR2(100),
  DATE_TRANSACTION DATE,
  STATUT          VARCHAR2(30),
  DESCRIPTION     CLOB,
  ID_PROJET       NUMBER,
  CONSTRAINT PK_FINANCE PRIMARY KEY (ID_TRANSACTION),
  CONSTRAINT FK_FINANCE_PROJET FOREIGN KEY (ID_PROJET)
    REFERENCES PROJET (ID_PROJET) ON DELETE CASCADE,
  CONSTRAINT CK_FINANCE_TYPE CHECK (TYPE_TRANS IN ('subvention','achat','salaire','remboursement','autre'))
);

CREATE SEQUENCE SEQ_FINANCE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE OR REPLACE TRIGGER BI_FINANCE
  BEFORE INSERT ON FINANCE
  FOR EACH ROW
BEGIN
  IF :NEW.ID_TRANSACTION IS NULL THEN
     SELECT SEQ_FINANCE.NEXTVAL INTO :NEW.ID_TRANSACTION FROM DUAL;
  END IF;
END;
/

-- 6) Table EVENEMENT
CREATE TABLE EVENEMENT (
  CODE_EVENEMENT   NUMBER        NOT NULL,
  NOM              VARCHAR2(200) NOT NULL,
  LIEU             VARCHAR2(200),
  DATE_EVENEMENT   DATE,
  CONSTRAINT PK_EVENEMENT PRIMARY KEY (CODE_EVENEMENT)
);

CREATE SEQUENCE SEQ_EVENEMENT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE OR REPLACE TRIGGER BI_EVENEMENT
  BEFORE INSERT ON EVENEMENT
  FOR EACH ROW
BEGIN
  IF :NEW.CODE_EVENEMENT IS NULL THEN
     SELECT SEQ_EVENEMENT.NEXTVAL INTO :NEW.CODE_EVENEMENT FROM DUAL;
  END IF;
END;
/

-- 7) Table LABORATOIRE
CREATE TABLE LABORATOIRE (
  ID_LABORATOIRE   NUMBER        NOT NULL,
  NOM              VARCHAR2(200) NOT NULL,
  THEMATIQUE       VARCHAR2(200),
  DISPONIBILITE    VARCHAR2(30), -- ex: 'disponible','indisponible'
  ADRESSE          VARCHAR2(400),
  ID_PROJET        NUMBER,
  CONSTRAINT PK_LABORATOIRE PRIMARY KEY (ID_LABORATOIRE),
  CONSTRAINT FK_LABORATOIRE_PROJET FOREIGN KEY (ID_PROJET)
    REFERENCES PROJET (ID_PROJET) ON DELETE SET NULL,
  CONSTRAINT CK_LAB_DISPO CHECK (DISPONIBILITE IN ('disponible','indisponible'))
);

CREATE SEQUENCE SEQ_LABORATOIRE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE OR REPLACE TRIGGER BI_LABORATOIRE
  BEFORE INSERT ON LABORATOIRE
  FOR EACH ROW
BEGIN
  IF :NEW.ID_LABORATOIRE IS NULL THEN
     SELECT SEQ_LABORATOIRE.NEXTVAL INTO :NEW.ID_LABORATOIRE FROM DUAL;
  END IF;
END;
/

-- 8) Table CONTRIBUER (relation N:M Chercheur <-> Projet)
CREATE TABLE CONTRIBUER (
  ID_CHERCHEUR   NUMBER NOT NULL,
  ID_PROJET       NUMBER NOT NULL,
  CONSTRAINT PK_CONTRIBUER PRIMARY KEY (ID_CHERCHEUR, ID_PROJET),
  CONSTRAINT FK_CONTRIBUER_CHERCHEUR FOREIGN KEY (ID_CHERCHEUR)
    REFERENCES CHERCHEUR (ID_CHERCHEUR) ON DELETE CASCADE,
  CONSTRAINT FK_CONTRIBUER_PROJET FOREIGN KEY (ID_PROJET)
    REFERENCES PROJET (ID_PROJET) ON DELETE CASCADE
);

-- 9) Table PARTICIPER (relation N:M Laboratoire <-> Evenement)
CREATE TABLE PARTICIPER (
  ID_LABORATOIRE   NUMBER NOT NULL,
  CODE_EVENEMENT   NUMBER NOT NULL,
  ROLE_LAB         VARCHAR2(100),
  CONSTRAINT PK_PARTICIPER PRIMARY KEY (ID_LABORATOIRE, CODE_EVENEMENT),
  CONSTRAINT FK_PARTICIPER_LAB FOREIGN KEY (ID_LABORATOIRE)
    REFERENCES LABORATOIRE (ID_LABORATOIRE) ON DELETE CASCADE,
  CONSTRAINT FK_PARTICIPER_EVENEMENT FOREIGN KEY (CODE_EVENEMENT)
    REFERENCES EVENEMENT (CODE_EVENEMENT) ON DELETE CASCADE
);

-- Quelques index utiles (exemples)
CREATE INDEX IDX_PUBLICATION_DATE ON PUBLICATION (DATE_PUBLICATION);
CREATE INDEX IDX_PROJET_DATES ON PROJET (DATE_DEBUT, DATE_FIN);
CREATE INDEX IDX_FINANCE_DATE ON FINANCE (DATE_TRANSACTION);

-- Modifications
alter table "SMARTPUB"."PARTICIPER" drop column "ROLE_LAB" cascade constraints;
alter table "SMARTPUB"."CONTRIBUER" drop column "DATE_DEBUT_CONTRIB" cascade constraints;
alter table "SMARTPUB"."CONTRIBUER" drop column "ROLE_CONTRIB" cascade constraints;

-- Fin du script
COMMIT;  